[mypy]
python_version = 3.12
mypy_path = backend:scripts
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_return_any = False
no_implicit_optional = True
check_untyped_defs = True
