package httpapi

const (
	routeHealthz                     = "/healthz"
	routeReadyz                      = "/readyz"
	routeMetrics                     = "/metrics"
	routeRuntimeMetrics              = "/metrics/runtime"
	routeMediaMTXAuth                = "/v1/mediamtx/auth"
	routeStreams                     = "/v1/streams"
	routeIceServers                  = "/v1/ice-servers"
	routeLegacyStreamStatus          = "/stream/status"
	routeDashboardIceServers         = "/api/v1/streams/ice-servers"
	routeDashboardStreamItemPrefix   = "/api/v1/streams/"
	routeDashboardStreamItemMetric   = "/api/v1/streams/{streamId}"
	routeDashboardStreams            = "/api/v1/streams"
	routeDevicePublishSessions       = "/api/v1/device/publish-sessions"
	routeDevicePublishSessionPrefix  = "/api/v1/device/publish-sessions/"
	routeAccountPublishSessions      = "/api/v1/account/publish-sessions"
	routeAccountPublishSessionPrefix = "/api/v1/account/publish-sessions/"
	routeSuffixPlayback              = "playback"
	routeSuffixPublish               = "publish"
	routeSuffixStatus                = "status"

	mediaMTXActionPlayback = "playback"
	mediaMTXActionPublish  = "publish"
	mediaMTXActionRead     = "read"
	playbackTokenQueryKey  = "playbackToken"
	publisherTokenQueryKey = "publisherToken"

	contentTypeHeader      = "Content-Type"
	jsonContentType        = "application/json"
	authorizationHeader    = "Authorization"
	deviceCredentialHeader = "X-GCS-Device-Credential"
	deviceUUIDHeader       = "X-GCS-Device-UUID"
	traceIDHeader          = "X-GCS-Trace-Id"
	forwardedForHeader     = "X-Forwarded-For"
	deprecationHeader      = "Deprecation"
	replacementRouteHeader = "X-GCS-Replacement-Route"

	jsonKeyDetail      = "detail"
	jsonKeyDeprecated  = "deprecated"
	jsonKeyChecks      = "checks"
	jsonKeyIceServers  = "iceServers"
	jsonKeyRuntime     = "runtime"
	jsonKeyName        = "name"
	jsonKeyReason      = "reason"
	jsonKeyRequired    = "required"
	jsonKeyReplacement = "replacement"
	jsonKeyService     = "service"
	jsonKeyStatus      = "status"
	jsonKeyStream      = "stream"
	jsonKeyStreams     = "streams"

	mediaControlServiceName          = "media-control"
	healthStatusOK                   = "ok"
	healthStatusDegraded             = "degraded"
	healthStatusError                = "error"
	legacyStreamReadyStatus          = "ready"
	legacyStreamStatusReplacement    = "/media-control/api/v1/streams"
	legacyStreamStatusDeprecatedFlag = "true"

	readyCheckStreamRegistry         = "stream_registry"
	readyCheckIceServers             = "ice_servers"
	readyCheckGrpcGateway            = "grpc_gateway"
	errStreamRegistryQueryFailed     = "stream registry query failed"
	errNoHealthyIceServers           = "no healthy ICE servers available"
	errGrpcGatewayUnavailable        = "grpc gateway unavailable"
	errAuthenticationRequiredMessage = "authentication required"
	errStreamAccessDeniedMessage     = "stream access denied"
	errStreamNotRegisteredMessage    = "stream is not registered"
	errPublisherAuthNotConfigured    = "publisher authorization is not configured"
	errDevicePublisherAuthRequired   = "device publisher authorization is required"
	errPublisherAuthFailed           = "publisher authorization failed"
	errPublishSessionInvalid         = "publish session request is invalid"
	errPublishSessionRenewalDenied   = "publish session renewal denied"
	errPlaybackAuthFailed            = "playback authorization failed"
)
