package httpapi

const (
	routeHealthz                   = "/healthz"
	routeReadyz                    = "/readyz"
	routeMetrics                   = "/metrics"
	routeRuntimeMetrics            = "/metrics/runtime"
	routeMediaMTXAuth              = "/v1/mediamtx/auth"
	routeStreams                   = "/v1/streams"
	routeIceServers                = "/v1/ice-servers"
	routeLegacyStreamStatus        = "/stream/status"
	routeDashboardIceServers       = "/api/v1/streams/ice-servers"
	routeDashboardStreamItemPrefix = "/api/v1/streams/"
	routeDashboardStreamItemMetric = "/api/v1/streams/{streamId}"
	routeDashboardStreams          = "/api/v1/streams"
	routeSuffixPlayback            = "playback"
	routeSuffixPublish             = "publish"
	routeSuffixStatus              = "status"

	mediaMTXActionPublish  = "publish"
	publisherTokenQueryKey = "publisherToken"

	contentTypeHeader      = "Content-Type"
	jsonContentType        = "application/json"
	authorizationHeader    = "Authorization"
	traceIDHeader          = "X-GCS-Trace-Id"
	deprecationHeader      = "Deprecation"
	replacementRouteHeader = "X-GCS-Replacement-Route"

	jsonKeyDetail      = "detail"
	jsonKeyDeprecated  = "deprecated"
	jsonKeyChecks      = "checks"
	jsonKeyIceServers  = "iceServers"
	jsonKeyRuntime     = "runtime"
	jsonKeyName        = "name"
	jsonKeyReason      = "reason"
	jsonKeyRequired    = "required"
	jsonKeyReplacement = "replacement"
	jsonKeyService     = "service"
	jsonKeyStatus      = "status"
	jsonKeyStream      = "stream"
	jsonKeyStreams     = "streams"

	mediaControlServiceName          = "media-control"
	healthStatusOK                   = "ok"
	healthStatusDegraded             = "degraded"
	healthStatusError                = "error"
	legacyStreamReadyStatus          = "ready"
	legacyStreamStatusReplacement    = "/media-control/api/v1/streams"
	legacyStreamStatusDeprecatedFlag = "true"

	readyCheckStreamRegistry         = "stream_registry"
	readyCheckIceServers             = "ice_servers"
	errStreamRegistryQueryFailed     = "stream registry query failed"
	errNoHealthyIceServers           = "no healthy ICE servers available"
	errAuthenticationRequiredMessage = "authentication required"
	errStreamAccessDeniedMessage     = "stream access denied"
	errStreamNotRegisteredMessage    = "stream is not registered"
	errPublisherAuthNotConfigured    = "publisher authorization is not configured"
	errPublisherAuthFailed           = "publisher authorization failed"
)
