spring:
  application:
    name: gcs-saker-auth-policy
  threads:
    virtual:
      enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
