package kr.co.a4ai.gcssaker.authpolicy.configuration

object AuthRuntimeEnvKeys {
    const val AUTH_POLICY_JWT_SECRET = "AUTH_POLICY_JWT_SECRET"
    const val AUTH_JWT_SECRET = "AUTH_JWT_SECRET"
    const val AUTH_POLICY_JWT_ISSUER = "AUTH_POLICY_JWT_ISSUER"
    const val AUTH_JWT_ISSUER = "AUTH_JWT_ISSUER"
    const val AUTH_POLICY_ACCESS_TOKEN_EXPIRE_MINUTES = "AUTH_POLICY_ACCESS_TOKEN_EXPIRE_MINUTES"
    const val AUTH_POLICY_REFRESH_TOKEN_EXPIRE_MINUTES = "AUTH_POLICY_REFRESH_TOKEN_EXPIRE_MINUTES"
    const val AUTH_POLICY_REFRESH_COOKIE_NAME = "AUTH_POLICY_REFRESH_COOKIE_NAME"
    const val AUTH_REFRESH_COOKIE_NAME = "AUTH_REFRESH_COOKIE_NAME"
    const val AUTH_POLICY_REFRESH_COOKIE_SECURE = "AUTH_POLICY_REFRESH_COOKIE_SECURE"
    const val AUTH_POLICY_REFRESH_COOKIE_SAMESITE = "AUTH_POLICY_REFRESH_COOKIE_SAMESITE"
    const val AUTH_REFRESH_COOKIE_SAMESITE = "AUTH_REFRESH_COOKIE_SAMESITE"
    const val AUTH_POLICY_ALLOWED_ORIGINS = "AUTH_POLICY_ALLOWED_ORIGINS"
    const val BACKEND_CORS_ALLOW_ORIGINS = "BACKEND_CORS_ALLOW_ORIGINS"
    const val AUTH_POLICY_ADMIN_USERNAME = "AUTH_POLICY_ADMIN_USERNAME"
    const val AUTH_POLICY_ADMIN_PASSWORD = "AUTH_POLICY_ADMIN_PASSWORD"
    const val AUTH_POLICY_ADMIN_COMPANY_ID = "AUTH_POLICY_ADMIN_COMPANY_ID"
    const val AUTH_POLICY_ADMIN_GROUP_ID = "AUTH_POLICY_ADMIN_GROUP_ID"
    const val AUTH_POLICY_OPERATOR_USERNAME = "AUTH_POLICY_OPERATOR_USERNAME"
    const val AUTH_POLICY_OPERATOR_PASSWORD = "AUTH_POLICY_OPERATOR_PASSWORD"
    const val AUTH_POLICY_OPERATOR_COMPANY_ID = "AUTH_POLICY_OPERATOR_COMPANY_ID"
    const val AUTH_POLICY_OPERATOR_GROUP_ID = "AUTH_POLICY_OPERATOR_GROUP_ID"
    const val AUTH_POLICY_SMOKE_USERNAME = "AUTH_POLICY_SMOKE_USERNAME"
    const val AUTH_POLICY_SMOKE_PASSWORD = "AUTH_POLICY_SMOKE_PASSWORD"
    const val AUTH_POLICY_SMOKE_COMPANY_ID = "AUTH_POLICY_SMOKE_COMPANY_ID"
    const val AUTH_POLICY_SMOKE_GROUP_ID = "AUTH_POLICY_SMOKE_GROUP_ID"
    const val AUTH_POLICY_SIGNUP_INVITES = "AUTH_POLICY_SIGNUP_INVITES"
    const val AUTH_POLICY_DEVICE_BOOTSTRAP_TOKENS = "AUTH_POLICY_DEVICE_BOOTSTRAP_TOKENS"
    const val AUTH_POLICY_REDIS_PRINCIPAL_CACHE_ENABLED = "AUTH_POLICY_REDIS_PRINCIPAL_CACHE_ENABLED"
    const val AUTH_POLICY_REDIS_REFRESH_SESSION_ENABLED = "AUTH_POLICY_REDIS_REFRESH_SESSION_ENABLED"
    const val AUTH_POLICY_JDBC_PERSISTENCE_ENABLED = "AUTH_POLICY_JDBC_PERSISTENCE_ENABLED"
    const val AUTH_POLICY_L1_AUTH_USER_CACHE_ENABLED = "AUTH_POLICY_L1_AUTH_USER_CACHE_ENABLED"
    const val AUTH_POLICY_REDIS_OPERATIONAL_EVENT_CACHE_ENABLED = "AUTH_POLICY_REDIS_OPERATIONAL_EVENT_CACHE_ENABLED"
    const val AUTH_POLICY_OPERATIONAL_EVENT_CACHE_KEY_PREFIX = "AUTH_POLICY_OPERATIONAL_EVENT_CACHE_KEY_PREFIX"
    const val AUTH_POLICY_OPERATIONAL_EVENT_CACHE_TTL_SECONDS = "AUTH_POLICY_OPERATIONAL_EVENT_CACHE_TTL_SECONDS"
    const val AUTH_POLICY_OPERATIONAL_EVENT_STALE_CACHE_KEY_PREFIX =
        "AUTH_POLICY_OPERATIONAL_EVENT_STALE_CACHE_KEY_PREFIX"
    const val AUTH_POLICY_OPERATIONAL_EVENT_STALE_CACHE_TTL_SECONDS =
        "AUTH_POLICY_OPERATIONAL_EVENT_STALE_CACHE_TTL_SECONDS"
    const val AUTH_POLICY_OPERATIONAL_EVENT_CACHE_TTL_JITTER_RATIO =
        "AUTH_POLICY_OPERATIONAL_EVENT_CACHE_TTL_JITTER_RATIO"
    const val AUTH_POLICY_REDIS_OPERATIONAL_READ_CACHE_ENABLED = "AUTH_POLICY_REDIS_OPERATIONAL_READ_CACHE_ENABLED"
    const val AUTH_POLICY_OPERATIONAL_READ_CACHE_KEY_PREFIX = "AUTH_POLICY_OPERATIONAL_READ_CACHE_KEY_PREFIX"
    const val AUTH_POLICY_OPERATIONAL_READ_CACHE_TTL_SECONDS = "AUTH_POLICY_OPERATIONAL_READ_CACHE_TTL_SECONDS"
    const val AUTH_POLICY_OPERATIONAL_READ_STALE_CACHE_KEY_PREFIX =
        "AUTH_POLICY_OPERATIONAL_READ_STALE_CACHE_KEY_PREFIX"
    const val AUTH_POLICY_OPERATIONAL_READ_STALE_CACHE_TTL_SECONDS =
        "AUTH_POLICY_OPERATIONAL_READ_STALE_CACHE_TTL_SECONDS"
    const val AUTH_POLICY_OPERATIONAL_READ_CACHE_TTL_JITTER_RATIO =
        "AUTH_POLICY_OPERATIONAL_READ_CACHE_TTL_JITTER_RATIO"
    const val AUTH_POLICY_RATE_LIMIT_ENABLED = "AUTH_POLICY_RATE_LIMIT_ENABLED"
    const val AUTH_POLICY_AUTH_RATE_LIMIT_PER_MINUTE = "AUTH_POLICY_AUTH_RATE_LIMIT_PER_MINUTE"
    const val AUTH_POLICY_ASYNC_POST_PROCESSING_ENABLED = "AUTH_POLICY_ASYNC_POST_PROCESSING_ENABLED"
    const val AUTH_POLICY_POST_PROCESSING_CORE_POOL_SIZE = "AUTH_POLICY_POST_PROCESSING_CORE_POOL_SIZE"
    const val AUTH_POLICY_POST_PROCESSING_MAX_POOL_SIZE = "AUTH_POLICY_POST_PROCESSING_MAX_POOL_SIZE"
    const val AUTH_POLICY_POST_PROCESSING_QUEUE_CAPACITY = "AUTH_POLICY_POST_PROCESSING_QUEUE_CAPACITY"
    const val AUTH_POLICY_ALLOW_LOCAL_DEFAULTS = "AUTH_POLICY_ALLOW_LOCAL_DEFAULTS"
}

object AuthRuntimeDefaults {
    const val LOCAL_JWT_SECRET = "local-auth-policy-secret-at-least-32-characters"
    const val LOCAL_ADMIN_PASSWORD = "admin-password"
    const val LOCAL_OPERATOR_PASSWORD = "correct-password"
    const val LOCAL_SMOKE_PASSWORD = "m7-smoke-pass"
    const val JWT_ISSUER = "gcs-saker"
    const val ACCESS_TOKEN_EXPIRE_MINUTES = 30L
    const val REFRESH_TOKEN_EXPIRE_MINUTES = 10_080L
    const val REFRESH_COOKIE_NAME = "gcs_saker_refresh"
    const val REFRESH_COOKIE_SAME_SITE = "lax"
    const val ADMIN_USERNAME = "admin01"
    const val OPERATOR_USERNAME = "operator01"
    const val SMOKE_USERNAME = "m7-smoke-viewer"
    const val COMPANY_ID = 1
    const val GROUP_ID = "co-a"
    const val SIGNUP_INVITES = "A4AI01:1:co-a"
    const val DEVICE_BOOTSTRAP_TOKENS = "LOCAL-DEVICE-BOOTSTRAP:co-a"
    const val OPERATIONAL_EVENT_CACHE_KEY_PREFIX = "gcs:ops-events:"
    const val OPERATIONAL_EVENT_CACHE_TTL_SECONDS = 5L
    const val OPERATIONAL_EVENT_STALE_CACHE_KEY_PREFIX = "gcs:ops-events:stale:"
    const val OPERATIONAL_EVENT_STALE_CACHE_TTL_SECONDS = 60L
    const val OPERATIONAL_READ_CACHE_KEY_PREFIX = "gcs:ops-read:"
    const val OPERATIONAL_READ_CACHE_TTL_SECONDS = 3L
    const val OPERATIONAL_READ_STALE_CACHE_KEY_PREFIX = "gcs:ops-read:stale:"
    const val OPERATIONAL_READ_STALE_CACHE_TTL_SECONDS = 30L
    const val CACHE_TTL_JITTER_RATIO = 0.2
    const val AUTH_RATE_LIMIT_PER_MINUTE = 60
    const val POST_PROCESSING_CORE_POOL_SIZE = 2
    const val POST_PROCESSING_MAX_POOL_SIZE = 4
    const val POST_PROCESSING_QUEUE_CAPACITY = 256
}
