# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcs/saker/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gcs/saker/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gcs/saker/v1/common.proto\x12\x0cgcs.saker.v1\"C\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x12\n\naltitude_m\x18\x03 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"I\n\x0bTimestamped\x12\x1c\n\x14observed_unix_millis\x18\x01 \x01(\x03\x12\x1c\n\x14received_unix_millis\x18\x02 \x01(\x03*\x97\x01\n\tAssetKind\x12\x1a\n\x16\x41SSET_KIND_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41SSET_KIND_DRONE\x10\x01\x12\x1b\n\x17\x41SSET_KIND_GROUND_ROBOT\x10\x02\x12\x1b\n\x17\x41SSET_KIND_FIXED_CAMERA\x10\x03\x12\x1e\n\x1a\x41SSET_KIND_OPERATOR_DEVICE\x10\x04*\x89\x01\n\x0bHealthState\x12\x1c\n\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x13\n\x0fHEALTH_STATE_OK\x10\x01\x12\x15\n\x11HEALTH_STATE_WARN\x10\x02\x12\x16\n\x12HEALTH_STATE_ERROR\x10\x03\x12\x18\n\x14HEALTH_STATE_OFFLINE\x10\x04\x42r\n kr.co.a4ai.gcssaker.contracts.v1P\x01ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcs.saker.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n kr.co.a4ai.gcssaker.contracts.v1P\001ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1'
  _globals['_ASSETKIND']._serialized_start=232
  _globals['_ASSETKIND']._serialized_end=383
  _globals['_HEALTHSTATE']._serialized_start=386
  _globals['_HEALTHSTATE']._serialized_end=523
  _globals['_GEOPOINT']._serialized_start=43
  _globals['_GEOPOINT']._serialized_end=110
  _globals['_VECTOR3']._serialized_start=112
  _globals['_VECTOR3']._serialized_end=154
  _globals['_TIMESTAMPED']._serialized_start=156
  _globals['_TIMESTAMPED']._serialized_end=229
# @@protoc_insertion_point(module_scope)
