# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcs/saker/v1/stream_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gcs/saker/v1/stream_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcs.saker.v1 import common_pb2 as gcs_dot_saker_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!gcs/saker/v1/stream_control.proto\x12\x0cgcs.saker.v1\x1a\x19gcs/saker/v1/common.proto\"?\n\tIceServer\x12\x0c\n\x04urls\x18\x01 \x03(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\t\"\x83\x02\n\x12StreamSessionEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x13\n\x0bstream_path\x18\x03 \x01(\t\x12\x1a\n\x12publisher_asset_id\x18\x04 \x01(\t\x12\x10\n\x08group_id\x18\x05 \x01(\t\x12(\n\x05state\x18\x06 \x01(\x0e\x32\x19.gcs.saker.v1.StreamState\x12\'\n\x04time\x18\x07 \x01(\x0b\x32\x19.gcs.saker.v1.Timestamped\x12,\n\x0bice_servers\x18\x08 \x03(\x0b\x32\x17.gcs.saker.v1.IceServerJ\x04\x08\t\x10\x15\"\xa5\x01\n\rStreamCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x17\n\x0ftarget_asset_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63ommand_type\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\'\n\x04time\x18\x06 \x01(\x0b\x32\x19.gcs.saker.v1.TimestampedJ\x04\x08\x07\x10\x15*\xb4\x01\n\x0bStreamState\x12\x1c\n\x18STREAM_STATE_UNSPECIFIED\x10\x00\x12\x1b\n\x17STREAM_STATE_PUBLISHING\x10\x01\x12\x19\n\x15STREAM_STATE_PLAYABLE\x10\x02\x12\x1d\n\x19STREAM_STATE_RECONNECTING\x10\x03\x12\x18\n\x14STREAM_STATE_STOPPED\x10\x04\x12\x16\n\x12STREAM_STATE_ERROR\x10\x05\x42r\n kr.co.a4ai.gcssaker.contracts.v1P\x01ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcs.saker.v1.stream_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n kr.co.a4ai.gcssaker.contracts.v1P\001ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1'
  _globals['_STREAMSTATE']._serialized_start=574
  _globals['_STREAMSTATE']._serialized_end=754
  _globals['_ICESERVER']._serialized_start=78
  _globals['_ICESERVER']._serialized_end=141
  _globals['_STREAMSESSIONEVENT']._serialized_start=144
  _globals['_STREAMSESSIONEVENT']._serialized_end=403
  _globals['_STREAMCOMMAND']._serialized_start=406
  _globals['_STREAMCOMMAND']._serialized_end=571
# @@protoc_insertion_point(module_scope)
