# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gcs/saker/v1/telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gcs/saker/v1/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gcs.saker.v1 import common_pb2 as gcs_dot_saker_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgcs/saker/v1/telemetry.proto\x12\x0cgcs.saker.v1\x1a\x19gcs/saker/v1/common.proto\"\x8d\x04\n\x11TelemetryEnvelope\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x04 \x01(\t\x12+\n\nasset_kind\x18\x05 \x01(\x0e\x32\x17.gcs.saker.v1.AssetKind\x12\'\n\x04time\x18\x06 \x01(\x0b\x32\x19.gcs.saker.v1.Timestamped\x12(\n\x08position\x18\x07 \x01(\x0b\x32\x16.gcs.saker.v1.GeoPoint\x12\x13\n\x0bheading_deg\x18\x08 \x01(\x01\x12\x11\n\tspeed_mps\x18\t \x01(\x01\x12\x17\n\x0f\x62\x61ttery_percent\x18\n \x01(\x01\x12)\n\x06health\x18\x0b \x01(\x0e\x32\x19.gcs.saker.v1.HealthState\x12\x19\n\x11\x61\x63tive_stream_ids\x18\x0c \x03(\t\x12+\n\x0c\x61ttitude_deg\x18\r \x01(\x0b\x32\x15.gcs.saker.v1.Vector3\x12/\n\x10gyro_rad_per_sec\x18\x0e \x01(\x0b\x32\x15.gcs.saker.v1.Vector3\x12)\n\naccel_mps2\x18\x0f \x01(\x0b\x32\x15.gcs.saker.v1.Vector3\x12\x1c\n\x14link_quality_percent\x18\x10 \x01(\x01J\x04\x08\x11\x10\x15\"@\n\x0eTelemetryBatch\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.gcs.saker.v1.TelemetryEnvelopeBr\n kr.co.a4ai.gcssaker.contracts.v1P\x01ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcs.saker.v1.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n kr.co.a4ai.gcssaker.contracts.v1P\001ZLgithub.com/gcs-saker/gcs-dashboard-app/contracts/gen/go/gcs/saker/v1;sakerv1'
  _globals['_TELEMETRYENVELOPE']._serialized_start=74
  _globals['_TELEMETRYENVELOPE']._serialized_end=599
  _globals['_TELEMETRYBATCH']._serialized_start=601
  _globals['_TELEMETRYBATCH']._serialized_end=665
# @@protoc_insertion_point(module_scope)
