CREATE TABLE IF NOT EXISTS auth_users (
    id INT NOT NULL PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    company_id INT NOT NULL,
    role VARCHAR(32) NOT NULL,
    group_id VARCHAR(64) NOT NULL,
    CONSTRAINT ux_auth_users_username UNIQUE (username),
    CONSTRAINT ux_auth_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS operational_events (
    id VARCHAR(128) NOT NULL PRIMARY KEY,
    occurred_at TIMESTAMP(3) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    category VARCHAR(64) NOT NULL,
    event_type VARCHAR(64),
    source_service VARCHAR(64),
    source VARCHAR(128) NOT NULL,
    message VARCHAR(1024) NOT NULL,
    connections INT NOT NULL,
    latency_ms BIGINT NOT NULL,
    throughput_mbps DOUBLE PRECISION NOT NULL,
    group_id VARCHAR(64) NOT NULL,
    stream_id VARCHAR(128),
    connection_id VARCHAR(128),
    ice_path VARCHAR(32),
    relay_fallback_reason VARCHAR(255)
);

ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(64);
ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS source_service VARCHAR(64);
ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS stream_id VARCHAR(128);
ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS connection_id VARCHAR(128);
ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS ice_path VARCHAR(32);
ALTER TABLE operational_events
    ADD COLUMN IF NOT EXISTS relay_fallback_reason VARCHAR(255);

CREATE INDEX IF NOT EXISTS ix_operational_events_group_occurred
    ON operational_events (group_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_operational_events_group_severity_occurred
    ON operational_events (group_id, severity, occurred_at);
CREATE INDEX IF NOT EXISTS ix_operational_events_group_stream_occurred
    ON operational_events (group_id, stream_id, occurred_at);

CREATE TABLE IF NOT EXISTS telemetry_latest (
    uuid VARCHAR(128) NOT NULL PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    altitude DOUBLE PRECISION NOT NULL,
    magnetic_x DOUBLE PRECISION NOT NULL,
    magnetic_y DOUBLE PRECISION NOT NULL,
    magnetic_z DOUBLE PRECISION NOT NULL,
    soc VARCHAR(32) NOT NULL,
    phone_battery_soc DOUBLE PRECISION NOT NULL,
    velocity DOUBLE PRECISION NOT NULL,
    total_distance DOUBLE PRECISION NOT NULL,
    epoch_time VARCHAR(32) NOT NULL,
    port_distance DOUBLE PRECISION NOT NULL,
    group_id VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_telemetry_latest_group_uuid
    ON telemetry_latest (group_id, uuid);

CREATE TABLE IF NOT EXISTS telemetry_history (
    uuid VARCHAR(128) NOT NULL,
    recorded_at TIMESTAMP(3) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    altitude DOUBLE PRECISION NOT NULL,
    magnetic_x DOUBLE PRECISION NOT NULL,
    magnetic_y DOUBLE PRECISION NOT NULL,
    magnetic_z DOUBLE PRECISION NOT NULL,
    soc VARCHAR(32) NOT NULL,
    phone_battery_soc DOUBLE PRECISION NOT NULL,
    velocity DOUBLE PRECISION NOT NULL,
    total_distance DOUBLE PRECISION NOT NULL,
    epoch_time VARCHAR(32) NOT NULL,
    port_distance DOUBLE PRECISION NOT NULL,
    group_id VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_telemetry_history_uuid_recorded
    ON telemetry_history (uuid, recorded_at);

CREATE TABLE IF NOT EXISTS gateway_assets (
    gateway_uuid VARCHAR(128) NOT NULL,
    id INT NOT NULL,
    cid VARCHAR(128) NOT NULL,
    uuid VARCHAR(128) NOT NULL,
    company_id INT NOT NULL,
    type VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    image_url VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    group_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (gateway_uuid, uuid)
);

CREATE INDEX IF NOT EXISTS ix_gateway_assets_gateway_group
    ON gateway_assets (gateway_uuid, group_id);

CREATE TABLE IF NOT EXISTS server_health_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    checked_at TIMESTAMP(3) NOT NULL,
    latency_ms BIGINT,
    message VARCHAR(512),
    group_id VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_server_health_group_checked
    ON server_health_snapshots (group_id, checked_at);
CREATE INDEX IF NOT EXISTS ix_server_health_group_service_checked
    ON server_health_snapshots (group_id, service_name, checked_at);

CREATE TABLE IF NOT EXISTS stream_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    started_at TIMESTAMP(3) NOT NULL,
    last_heartbeat_at TIMESTAMP(3) NOT NULL,
    stopped_at TIMESTAMP(3),
    group_id VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_stream_sessions_group_stream_heartbeat
    ON stream_sessions (group_id, stream_id, last_heartbeat_at);
CREATE INDEX IF NOT EXISTS ix_stream_sessions_group_status_heartbeat
    ON stream_sessions (group_id, status, last_heartbeat_at);
