CREATE TABLE IF NOT EXISTS organization_groups (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(32) NOT NULL,
    parent_id VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organization_groups_parent
        FOREIGN KEY (parent_id) REFERENCES organization_groups (id),
    CONSTRAINT ck_organization_groups_not_self_parent
        CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX IF NOT EXISTS ix_organization_groups_parent_status
    ON organization_groups (parent_id, status);

CREATE TABLE IF NOT EXISTS organization_group_closure (
    ancestor_group_id VARCHAR(64) NOT NULL,
    descendant_group_id VARCHAR(64) NOT NULL,
    depth INT NOT NULL,
    PRIMARY KEY (ancestor_group_id, descendant_group_id),
    CONSTRAINT fk_group_closure_ancestor
        FOREIGN KEY (ancestor_group_id) REFERENCES organization_groups (id),
    CONSTRAINT fk_group_closure_descendant
        FOREIGN KEY (descendant_group_id) REFERENCES organization_groups (id),
    CONSTRAINT ck_group_closure_depth
        CHECK (depth >= 0)
);

CREATE INDEX IF NOT EXISTS ix_group_closure_descendant_depth
    ON organization_group_closure (descendant_group_id, depth);

CREATE TABLE IF NOT EXISTS registered_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid VARCHAR(128) NOT NULL,
    mac_hash VARCHAR(128),
    group_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    credential_id VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP(3),
    CONSTRAINT ux_registered_devices_uuid UNIQUE (device_uuid),
    CONSTRAINT fk_registered_devices_group
        FOREIGN KEY (group_id) REFERENCES organization_groups (id)
);

CREATE INDEX IF NOT EXISTS ix_registered_devices_group_status
    ON registered_devices (group_id, status);
CREATE INDEX IF NOT EXISTS ix_registered_devices_mac_hash
    ON registered_devices (mac_hash);
