ALTER TABLE auth_users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('auth_users', 'id'),
    COALESCE((SELECT MAX(id) FROM auth_users), 1),
    EXISTS (SELECT 1 FROM auth_users)
);

ALTER TABLE operational_events
    ALTER COLUMN occurred_at TYPE TIMESTAMPTZ(3) USING occurred_at AT TIME ZONE 'UTC';
ALTER TABLE telemetry_history
    ALTER COLUMN recorded_at TYPE TIMESTAMPTZ(3) USING recorded_at AT TIME ZONE 'UTC';
ALTER TABLE gateway_assets
    ALTER COLUMN created_at TYPE TIMESTAMPTZ(3) USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ(3) USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE server_health_snapshots
    ALTER COLUMN checked_at TYPE TIMESTAMPTZ(3) USING checked_at AT TIME ZONE 'UTC';
ALTER TABLE stream_sessions
    ALTER COLUMN started_at TYPE TIMESTAMPTZ(3) USING started_at AT TIME ZONE 'UTC',
    ALTER COLUMN last_heartbeat_at TYPE TIMESTAMPTZ(3) USING last_heartbeat_at AT TIME ZONE 'UTC',
    ALTER COLUMN stopped_at TYPE TIMESTAMPTZ(3) USING stopped_at AT TIME ZONE 'UTC';
